### ISSUE TITLE
Nodejs (V8 engine) compiler bug report

### ISSUE THREAD

**Issue by siroossheikhi** [nodejs/nodejs.org#3411] opened 2020-09-29 12:06 UTC
Hi Guys
Today while I was coding realized destructuring assignment will not work correctly when write immediately after close brace of object defining without semicolon.
You can re-create bug using below sample codes. my node version is 12.16.2

**Close brace of object defining without semicolon**
> _let a,b,c
> a={x:1} //<~~~without semicolon
> [b, c] = [1, 2]
> console.log(b)
> console.log(c)_

**above code will return**
> _undefined
> undefined_

**Close brace of object defining with semicolon**
> _let a,b,c
> a={x:1}; //<~~~with semicolon
> [b, c] = [1, 2]
> console.log(b)
> console.log(c)_

**above code will return**
> _1
> 2_

**Close brace of if statement**
> let a,b,c
> if(1===1){
>   a = 1
> } //<~~~without semicolon
> [b, c] = [1, 2]
> console.log(b)
> console.log(c)

**above code will return**
> _1
> 2_

**Comment by Trott** [comment] 2020-09-29 12:53
HI! This is not a bug. This is how [automatic semicolon insertion](https://2ality.com/2011/05/semicolon-insertion.html) (ASI) works in JavaScript. You will get the exact same result if you run your code in a browser.

It isn't about the destructuring assignment. It's about the line after it that starts with `[`.  That prevents ASI in your first example because it is interpreted as an index for the object literal on the previous line. You don't see it with the closing brace for the `if` statement because that can't have an index and a semicolon need not be inserted there in any event for the code to work.

**Closed by Trott** 2020-09-29 12:53 UTC
