### ISSUE TITLE
Broken links to release downloads on Previous Releases page (missing trailing '/')

### ISSUE THREAD

**Issue by weslord** [nodejs/nodejs.org#6110] opened 2023-11-11 22:28 UTC
### URL:

https://nodejs.org/en/about/previous-releases

### Browser Name:

Firefox

### Browser Version:

119.0

### Operating System:

Ubuntu 23.10

### How to reproduce the issue:

The "Releases" links in the table on https://nodejs.org/en/about/previous-releases lead to a simple 404 page.

For example, the Node.js 18.18.2 row links to
https://nodejs.org/download/release/v18.18.2 <- 404

Looks like there's a missing trailing '/'
https://nodejs.org/download/release/v18.18.2/ <- works

**Comment by ovflowd** [comment] 2023-11-11 22:46
I dont think this is a bug on the Website. We recently (last days) switched /download/ endpoint to use a new technology for serving those paths (aka Cloudflare R2 + Cloudflare Workers)

I believe the actual issue lies there cc @flakey5

**Comment by flakey5** [comment] 2023-11-11 22:59
Yeah it has to deal with how we detect whether or not a path is pointing to a directory or a file in the worker. For instance with `https://nodejs.org/download/release/v18.18.2`, it sees the `.2` at the end of the url and thinks it's the file extension.

Code for it is here https://github.com/nodejs/release-cloudflare-worker/blob/cb2b5306a9c524ef5bda6c1722ffedf5576937a1/src/util.ts#L209C76-L209C76.

Interestingly someone added to it so that paths such as `https://nodejs.org/download/release/latest-v21.x` work as intended. I think the fix for this would be to add another heuristic that if the characters after the final `.` in a path are numbers it's considered a directory

**Comment by flakey5** [comment] 2023-11-11 23:04
I think #6111 is still good, one less request hitting the worker since we won't need to redirect

**Comment by ovflowd** [comment] 2023-11-11 23:23
Right, but we would be checking if the last "." (Dot) is followed by a number? Is that enough of a check?

**Comment by flakey5** [comment] 2023-11-11 23:24
> Right, but we would be checking if the last "." (Dot) is followed by a number? Is that enough of a check?

Yeah I'm getting a pr for adding the additional check to the worker ready now

**Comment by weslord** [comment] 2023-11-11 23:42
> Right, but we would be checking if the last "." (Dot) is followed by a number? Is that enough of a check?

Do you serve man pages anywhere?

---

Interestingly, similar `dist/` urls seems to redirect
https://nodejs.org/dist/v18.18.2

**Comment by ovflowd** [comment] 2023-11-11 23:46
> > Right, but we would be checking if the last "." (Dot) is followed by a number? Is that enough of a check?
> 
> 
> 
> Do you serve man pages anywhere?
> 
> 
> 
> ---
> 
> 
> 
> Interestingly, similar `dist/` urls seems to redirect
> 
> https://nodejs.org/dist/v18.18.2

No. And /dist is not under this new worker yet.

**Comment by ljharb** [comment] 2023-11-12 04:51
It's fine to change docs so they point to the canonical URL, but old URLs need to work forever - it's a core principle of the web. meaning, the links that lack the trailing slash need to redirect to have the trailing slash, i suppose?

**Closed as completed** 2023-11-12 06:04 UTC

**Comment by ljharb** [comment] 2023-11-12 06:08
Awesome, thanks!
