### ISSUE TITLE
Cannot read the webpage text

### ISSUE THREAD

**Issue by philipheinser** [nodejs/nodejs.org#6520] opened 2024-03-24 10:57 UTC
### URL:

https://nodejs.org/en

### Browser Name:

Safari

### Browser Version:

19618.1.15.11.12

### Operating System:

MacOS

### How to reproduce the issue:

Background makes the text not readable. Also the old website had always easy download buttons for latest and lts really hard to see what version I download. I would suggest to bring back the 2 easy big buttons.

<img width="590" alt="Screenshot 2024-03-24 at 10 53 13" src="https://github.com/nodejs/nodejs.org/assets/3705499/50e3d4a0-a0a2-4e76-8a40-b56cdd505ec3">

**Comment by AugustinMauroy** [comment] 2024-03-24 11:03
Yep that awful but we cannot do something it's an bug from WebKit

**Comment by philipheinser** [comment] 2024-03-24 11:49
@AugustinMauroy Just get rid of the black grid or give the text a background color would be easy fixes could also be done only in webkit if the issue only exists there? Even if the bug comes from a browser don't you want your users to have a good experience?

**Comment by AugustinMauroy** [comment] 2024-03-24 11:57
I'm going to look into putting a background on the text just on safari.

If we add code for that it's will look like that:

```css
@media screen and (-webkit-min-device-pixel-ratio:0) {
  .selector {
    @apply flex
         flex-col
         bg-withe
  }
}```

**Comment by ovflowd** [comment] 2024-03-24 12:57
> @AugustinMauroy Just get rid of the black grid or give the text a background color would be easy fixes could also be done only in webkit if the issue only exists there? Even if the bug comes from a browser don't you want your users to have a good experience?

This issue only happens on very edge scenarios and old versions of Safari. Most of the time, it is non-reproducible.

Even on my iPhone and Mac this is not reproducible 🤷

**Comment by philipheinser** [comment] 2024-03-24 15:53
@ovflowd Its the newest version of safari. Without any extensions.

<img width="1717" alt="Screenshot 2024-03-24 at 15 50 51" src="https://github.com/nodejs/nodejs.org/assets/3705499/ddbab2b1-b019-4c28-8250-fbe900f01e73">

**Comment by ovflowd** [comment] 2024-03-24 15:55
> @ovflowd Its the newest version of safari. Without any extensions.
> 
> <img alt="Screenshot 2024-03-24 at 15 50 51" width="1717" src="https://private-user-images.githubusercontent.com/3705499/316321523-ddbab2b1-b019-4c28-8250-fbe900f01e73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyOTU5ODQsIm5iZiI6MTcxMTI5NTY4NCwicGF0aCI6Ii8zNzA1NDk5LzMxNjMyMTUyMy1kZGJhYjJiMS1iMDE5LTRjMjgtODI1MC1mYmU5MDBmMDFlNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjRUMTU1NDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE0MWIyMzA3ZmUzNmNjYzUyZmZjYzNkMDg4YTc1NzRiMDg1OGFkNjk3YjA3YmJhOGZjNTM5MzExOTYzZWIzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xb44agX8uIdacfqxXhs0jEqzmANH6gYbvoDtUgt3ppo">

Unfortunately I'm not able to reproduce it. Do you have some specific accessibility setting? Reduced animations, or higher contrast settings or something?

**Comment by ovflowd** [comment] 2024-03-24 15:56
(I can't fix a bug that doesn't happen to me, as I don't know what even to look for, the gradient has no setting at all or colour that would make it look like the way it is looking to you)

So any extra detail would be more than appreciated!

**Comment by canerakdas** [comment] 2024-03-24 17:34
I was able to reproduce it, interestingly, it downloads the hexagon svg 7 times;

<img width="600" alt="image" src="https://github.com/nodejs/nodejs.org/assets/14062599/a38c5a96-411d-4ab9-9d83-9ff259d0d030">

<img width="600" alt="image" src="https://github.com/nodejs/nodejs.org/assets/14062599/f38c8822-3c87-45a0-90b8-bdd8ad2738e3">

<img width="600" alt="image" src="https://github.com/nodejs/nodejs.org/assets/14062599/2bbdcbe2-b6b1-486f-927f-5b639ef318a6">

<img width="600" alt="image" src="https://github.com/nodejs/nodejs.org/assets/14062599/a505402e-935a-4391-bf12-385fede58149">

The chunks are the same but the behavior seems different, it's a bit interesting 🤔

**Comment by ovflowd** [comment] 2024-03-24 22:55
Reopening as one of our collaborators was able to reproduce it and they can work on a fix!

**Comment by canerakdas** [comment] 2024-03-24 23:45
I think this is due to an issue on the Webkit side, as @AugustinMauroy  mentioned. After switching to Reader mode, the background color is somehow reflected in our semi-transparent hexagons.

You can reproduce this via the following steps;

1. `Command + Shift + r`
2. `Command + r`
3. Click a URL bar and redirect the site

https://github.com/nodejs/nodejs.org/assets/14062599/fb8d52af-b5f0-4ca8-bcc5-0eb9c8bba2fc

**Comment by ovflowd** [comment] 2024-03-24 23:47
Can we confirm this is a WebKit issue? Should we open a bug report on WebKit?

**Comment by AugustinMauroy** [comment] 2024-03-25 08:59
> Can we confirm this is a WebKit issue? Should we open a bug report on WebKit?

Honestly, I can't see what would cause this in our code. Secondly, it's very random. I haven't managed to make a procedure to make this bug appear. And I haven't managed to make it disappear either.

So for me it's issue on SVG rendering from WebKit.

**Comment by canerakdas** [comment] 2024-03-25 16:47
I have opened a bug report on WebKit, you can track it down with the following URL;

https://bugs.webkit.org/show_bug.cgi?id=271615

**Comment by AugustinMauroy** [comment] 2024-04-25 15:41
I close this pr because we no longer display the SVG using css. But I'm keeping an eye on the issues for webkit.

**Closed as completed by AugustinMauroy** 2024-04-25 15:41 UTC
