### ISSUE TITLE
node 18.10.0 for linux return 404

### ISSUE THREAD

**Issue by danyel** [nodejs/nodejs.org#5153] opened 2023-03-16 12:01 UTC
### URL:

https://nodejs.org/dist/v18.10.0/node-v18.10.0-linux-x64.tar.gz

### Browser Name:

any

### Browser Version:

any

### Operating System:

any

### How to reproduce the issue:

try to download https://nodejs.org/dist/v18.10.0/node-v18.10.0-linux-x64.tar.gz and it returns a 404

**Comment by danyel** [comment] 2023-03-16 12:02
this version is used when download it via a maven plugin

**Comment by ovflowd** [comment] 2023-03-16 12:15
Duplicate of #5149

**Comment by ovflowd** [comment] 2023-03-16 12:15
Before opening an issue, does it hurt quickly look if a similar exist? 😅

**Closed as not planned by ovflowd** 2023-03-16 12:15 UTC
