### ISSUE TITLE
nodejs.org's i18n is not working

### ISSUE THREAD

**Issue by yeying-xingchen** [nodejs/nodejs.org#6553] opened 2024-03-26 12:04 UTC
### URL:

https://nodejs.org

### Browser Name:

Edge

### Browser Version:

123.0.2420.53

### Operating System:

Windows11 26080.1100

### How to reproduce the issue:

When I visit the address of the nodejs.org language other than English, the website will return 404, therefore, I opened the en page, only to find that in the select language button, there is only one option in English, however, on crowdin, the Chinese Simplified has been translated 98%, at the same time, I also saw the relevant requests for other languages in the issue of this repository, I hope to restore it as soon as possible, thank you!

**Comment by bmuenzenmeyer** [comment] 2024-03-26 14:37
internationalization is not broken - it is intentionally not enabled while we sort out some technical and process issues between us and crowdin. 

we owe the community more information, as it's an active concern we are working on as time allows

**Comment by ovflowd** [comment] 2024-03-26 16:27
Closing this issue as there's no actionable for us. The Internationalisation Engine works, and we've tested it multiple times. The issue is that we have disabled i18n for now, due to our internationalisation platform (Crowdin) having Markdown formatting issues which break the stylistic aspect of our code and even at times break builds.

**Closed as not planned by ovflowd** 2024-03-26 16:27 UTC
Labels: i18n
