### ISSUE TITLE
the connection to this website is not secure

### ISSUE THREAD

**Issue by mrmunch** [nodejs/nodejs.org#4600] opened 2022-05-11 14:18 UTC
While "nodejs.org" is secure, I have an issue when I try to download a file from your website, for example:
https://nodejs.org/dist/v16.14.2/node-v16.14.2-win-x64.zip
This gives me a "the connection to this website is not secure" message (see screenshot).
![image](https://user-images.githubusercontent.com/12833236/167871873-c7767b1a-ef4b-4647-9941-423f467c1908.png)

Please secure this connection, thank you.

**Comment by Trott** [comment] 2022-05-11 14:28
That's correct. You'll need to validate the SHASUM if you want to confirm the file has been downloaded without corruption etc. This was probably left that way for performance/cost reasons at some point but I suspect a lot of other download-our-large-tarball open source options followed the same practice. But a quick look at Python and PHP show that they use https for their tarball downloads, and the costs/performance issues aren't as relevant as they once were.  @nodejs/build

**Comment by richardlau** [comment] 2022-05-11 14:46
> That's correct. You'll need to validate the SHASUM if you want to confirm the file has been downloaded without corruption etc. This was probably left that way for performance/cost reasons at some point but I suspect a lot of other download-our-large-tarball open source options followed the same practice. But a quick look at Python and PHP show that they use https for their tarball downloads, and the costs/performance issues aren't as relevant as they once were. @nodejs/build

I'm confused. Our downloads are via https unless you're specifically going via http://unencrypted.nodejs.org (which you should not be).

**Comment by Trott** [comment] 2022-05-11 22:24
> I'm confused. Our downloads are via https unless you're specifically going via http://unencrypted.nodejs.org (which you should not be).

Oh, you're right (unsurprisingly). My mistake. Sorry.

I'm unable to duplicate the problem that @mrmunch is seeing. We'll need more information.

**Comment by de3124** [comment] 2022-05-12 09:00
Hi @Trott 
I'm in a corporate network and we use zScaler (but the zScaler cert is locally installed on my machine).
What else information could I give you?

**Comment by sxa** [comment] 2022-05-12 09:38
Which certificate is your web browser presenting you with and which browser is it? I don't think anyone else can reproduce this problem.

**Comment by jaas666** [comment] 2022-05-13 19:19
> Hi @Trott 
> I'm in a corporate network and we use zScaler (but the zScaler cert is locally installed on my machine).
> What else information could I give you?

Your issue is most likely caused by the use of a zScaler SSL inspection rule.

Basically zScaler is sitting between your device and nodejs.org server. In order to inspect ssl traffic it establishes a connection to the requested server and validates their certificate then uses a self assigned certificate to establish the connection from your device to the zScaler.

Your device is never seeing the nodejs.org certificate. You can easily confirm this by looking at the info on the presented  certificate. It probably is a self generated zScaler certificate.

In order to get rid of the message your device needs to trust the zScaler CA or the  zScaler device needs to provide a certificate issued by your corporate CA, if any.

[Here's better explained](https://help.zscaler.com/zia/about-ssl-inspection) on zScaler website.

If that's indeed the case this is not a nodejs.org issue nor something that can be fixed on their side.

**Comment by Trott** [comment] 2022-05-13 19:38
Optimistically closing this. Comment or re-open if there is more to this. Thanks.

**Closed as completed by Trott** 2022-05-13 19:38 UTC
