### ISSUE TITLE
Website analytics

### ISSUE THREAD

**Issue by feross** [nodejs/nodejs.org#1268] opened 2017-06-15 22:02 UTC
How popular are the Node.js docs? I'm curious about the total monthly page views, unique visitors, and time spent on site for everything in `/docs/api`.

It would also be interesting to know how many page views the website as a whole receives.

**Comment by fhemberger** [comment] 2017-06-16 04:05
Here are the stats compared for the last two months:

![](https://user-images.githubusercontent.com/153481/27211449-a05e2e48-5259-11e7-84c4-d1e9c7d5c500.png)

Hope that helps, if you need further details, please let me know.

**Comment by feross** [comment] 2017-06-16 06:05
@fhemberger Thank you. Can you confirm if those counts are for the specific individual pages or for all of the pages that are in subfolders, e.g. `/en/docs/*`?

It appears that those numbers may be just for the individual pages, excluding most of the hits in the subfolders.

**Comment by fhemberger** [comment] 2017-06-17 13:08
@feross Sorry, those were the stats of /docs/, not the API docs. D'oh!

Here are the (hopefully) correct ones for the same time period:

![](https://user-images.githubusercontent.com/153481/27253116-9c0aa928-536e-11e7-82e8-0d4f614e4032.png)

The problem here is that `/latest/` doesn't redirect to `/latest-vX.X`, which influences the stats

**Comment by feross** [comment] 2017-06-19 08:09
@fhemberger Thanks for the updated stats. I still think something doesn't look right.

How can it be that the docs were viewed only a few hundred times? I believe the stats are showing the number of times that the *specific page* is loaded, not including pages that are nested within.

For example, hits to https://nodejs.org/dist/latest-v8.x/ are included, but hits to https://nodejs.org/dist/latest-v8.x/docs/api/ and https://nodejs.org/dist/latest-v8.x/docs/api/buffer.html are **not** being included.

Otherwise, I don't see how the stats could be so low, but please correct me if I'm missing something.

**Comment by feross** [comment] 2017-06-19 08:10
Actually, it appears that the API docs are missing the Google Analytics script.

I see that these pages request the script:

https://nodejs.org/en/
https://nodejs.org/en/docs/

But these pages do not:

https://nodejs.org/dist/latest-v8.x/docs/api/
https://nodejs.org/dist/latest-v8.x/docs/api/buffer.html

@fhemberger Can you also confirm this?

**Comment by fhemberger** [comment] 2017-06-19 08:29
@feross Yes, I can confirm this. There's only a comment `<!-- __TRACKING__ -->` at the end of the page, but the actual tracking code seems to be missing.

Should have been replaced during the build process: [/tools/doc/html.js#L155](https://github.com/nodejs/node/blob/0584aeb30a97d8ca81f242f4ddc05a0c6f9b7684/tools/doc/html.js#L155). Looks like `/tools/doc/generate.js` was called without the `--analytics=…` parameter, which seems to be the case for all `latest-vX.x` versions.

Just found an issue for that, dating back to January:
https://github.com/nodejs/node/issues/11050

**Comment by phillipj** [comment] 2017-06-19 08:38
That's right, the docs do have support for GA tracking, but it hasn't been enabled yet because I've never been able to find where that `--analytics` parameter have to be added. Ref the issue @fhemberger just mentioned ^.

**Comment by fhemberger** [comment] 2017-06-19 08:50
@phillipj Found it:
https://github.com/nodejs/node/blob/master/Makefile#L463

Referenced here:
https://github.com/nodejs/node/blob/master/Makefile#L501

**Comment by phillipj** [comment] 2017-06-19 08:56
@fhemberger: yeah, that's the $ENV variable that allows the GA code to be set when building the docs. The problem is that I haven't found where/whom `$ make doc` is **actually** run. Assumed it was some hidden CI somewhere that's only visible to those cutting new versions, but as said, never got an answer from the ones that probably has the correct answer..

Please feel free to help pinging "someone" ;)

**Comment by fhemberger** [comment] 2017-06-19 09:05
@nodejs/jenkins-admins to the resuce!

**Comment by rvagg** [comment] 2017-06-19 09:50
yep, one of the jenkins admins can indeed do that, is `DOCS_ANALYTICS="UA-67020396-1"` enough for this?

**Comment by rvagg** [comment] 2017-06-19 09:53
<img width="331" alt="screenshot 2017-06-19 19 52 33" src="https://user-images.githubusercontent.com/495647/27279730-e741f782-5528-11e7-9e04-189a2ebfbf30.png">

That's in there now, someone keep an eye on the next release and make sure that it comes out as you expect. As a test you should also see them show up in the nightlies and v8-canary releases from now on too.

**Comment by fhemberger** [comment] 2017-06-19 10:02
@rvagg Thanks, if everything works out, can we re-generate existing docs (at least `latest-vX.x`) as well?

**Comment by phillipj** [comment] 2017-06-19 10:05
Thanks @rvagg! 👍

**Comment by rvagg** [comment] 2017-06-19 10:08
in theory we could regenerate them all but perhaps we'd be better off doing a `sed` replacement on the server instead, do we have something obvious to grep for or is that all stripped out for non-GA docs?

**Comment by fhemberger** [comment] 2017-06-19 10:12
@rvagg There's an HTML comment `<!-- __TRACKING__ -->` at the end of the page. It is replaced by the doc build, so that should be fine to grep.

**Comment by phillipj** [comment] 2017-06-19 10:15
Which should be replaced with what is produced by [nodejs/node/tools/doc/html.js#L171](https://github.com/nodejs/node/blob/master/tools/doc/html.js#L171), e.g: 

```html
<script src="assets/dnt_helper.js"></script>
<script>
  if (!_dntEnabled()) {
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;
    i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},
    i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];
    a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,
    'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-67020396-1', 'auto');
    ga('send', 'pageview');
  }
</script>
```

**Comment by feross** [comment] 2017-06-20 23:52
The latest nightly (generated today) still shows a `<!-- __TRACKING__ -->` comment instead of the Google Analytics script. See: https://nodejs.org/download/nightly/v9.0.0-nightly20170620d2913384aa/docs/api/

@rvagg Looks like this still might not be working?

**Comment by rvagg** [comment] 2017-06-21 06:13
![screen shot 2017-06-20 at 11 12 24 pm](https://user-images.githubusercontent.com/495647/27369710-052f94f8-560e-11e7-8f7e-a8136cf9e5bb.png)

I'm guessing that it's something in the Makefile that's preventing this from propagating all the way through. Investigating.

**Comment by rvagg** [comment] 2017-06-21 07:23
OK, so it's because we run `make doc-upload` straight after `make tar-upload` which depends on `doc` so has already built the docs without tracking. The logs even show it basically doing a 3 line noop before uploading.

Inserting a `make docclean` just before the `make doc-upload` _should_ do the trick, works locally for me at least. I've done it now on the release job, so keep an eye on the next nightly!

**Comment by rvagg** [comment] 2017-06-21 22:53
https://nodejs.org/download/nightly/v9.0.0-nightly2017062132c7f114c5/docs/api/ bingo

https://github.com/nodejs/node/pull/13861 8.1.2 will probably be the first opportunity to test this on an actual release but as it's exactly the same process I don't imagine there'll be any problem. This issue can either be closed now or you could wait to confirm.

**Comment by feross** [comment] 2017-06-22 00:51
@rvagg Awesome! One question: will analytics be added to previous release docs once 8.1.2 is released? Or will it only be on 8.1.2 and later docs?

@fhemberger I'm still curious about the actual traffic numbers to Node.js docs, but I guess we have to wait a while to collect some data now :) Can you add me to the Google Analytics account (read-only access) so I can poke around? My email address is `feross@gmail.com`.

**Comment by fhemberger** [comment] 2017-06-26 09:48
@mikeal Can you please add @feross to Google Analytics?

**Comment by mikeal** [comment] 2017-07-03 19:42
I don't think I have access anymore, it was linked to my linuxfoundation.org Google Account which I don't have anymore :( Maybe @ZibbyKeaton can help.

**Comment by ZibbyKeaton** [comment] 2017-07-03 20:55
I do not have sufficient permissions to do that. Do you know anyone else that might @mikeal ?

**Comment by fhemberger** [comment] 2017-07-04 01:34
Ok, looks like I have sufficient permissions. Just wanted to make sure it's okay, will add him later.

**Comment by fhemberger** [comment] 2017-07-04 05:17
@mikeal Yes, you're still registered with your linuxfoundation.org account. Do you want me to change that?

**Comment by fhemberger** [comment] 2017-11-04 11:21
Closing this issue for now, feel free to reopen if there are further questions regarding analytics.

**Closed as completed by fhemberger** 2017-11-04 11:21 UTC
