### ISSUE TITLE
NodeJS download very slow

### ISSUE THREAD

**Issue by mgoroff1126** [nodejs/nodejs.org#6043] opened 2023-10-24 15:48 UTC
### URL:

https://nodejs.org/dist/

### Browser Name:

Edge

### Browser Version:

118.0.2088.61

### Operating System:

Windows 11 Enterprise 22H2

### How to reproduce the issue:

Downloading https://nodejs.org/dist/v14.17.6/node-v14.17.6-linux-x64.tar.gz and https://nodejs.org/dist/v21.0.0/node-v21.0.0-linux-x64.tar.gz from Jenkins and from browser is very slow causing Jenkins jobs to fail with a timeout. Running at 11:19 AM EST today Oct 24, 2023. This has happened randomly over the past several weeks. After a period of time, the downloads resume to work at normal speed.

**Comment by bmuenzenmeyer** [comment] 2023-10-24 15:50
duplicate of https://github.com/nodejs/nodejs.org/issues/4495

**Closed as not planned by bmuenzenmeyer** 2023-10-24 15:50 UTC
