### ISSUE TITLE
Create `InlineSelect` variant of the `Select` component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5913] opened 2023-09-29 13:06 UTC
> [!note] 
> If #5909 is not yet done, this issue must wait

Enhance the `Select` component introduced with https://github.com/nodejs/nodejs.org/issues/5909 to have an `InlineSelect` variant. Use the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=433-3390&mode=dev). 

This component is a select with additional data in the list of options.

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

---

### Details

<img width="616" alt="image" src="https://github.com/nodejs/nodejs.org/assets/298435/fa381199-d919-4a92-9314-c0538ea1eca7">

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Alter the `Select` component found within the [`components/common/select` directory](https://github.com/nodejs/nodejs.org/tree/main/components/common/select) 
- Add to the storybook story file `components/common/Select/index.stories.tsx` which exercises each of the component's states.

Suggested additional props include or alter:

- `inline` (boolean): changes the render mode.
  - when present, visually hides the label
  - think through how to support accessibility here
- `values`  should now also accept an array of objects:
```js
[
    {
        value: "MacOS",
        iconImageUrl: "path/to/image"
    },
    ...
]
``` 
- the `iconImageUrl` can be added to radix's `Select.Item` API

```
          <Select.Item>
            <Select.ItemText />
            <Select.ItemIndicator />
          </Select.Item>
```

There are 2 states to capture within styles and stories:

- Light
- Dark

**Comment by premtw** [comment] 2023-09-30 02:54
Hi @bmuenzenmeyer I can work on this, once the [issue](https://github.com/nodejs/nodejs.org/issues/5909) has been completed.

**Comment by mrkirthi-24** [comment] 2023-09-30 07:20
Hi @bmuenzenmeyer Can i work on this issue?

**Comment by ovflowd** [comment] 2023-09-30 11:27
This Issue is still on Backlog, so please wait for the other Issue to get completed :)

**Comment by PavanaSakethaRam** [comment] 2023-10-04 07:01
@bmuenzenmeyer Is issue still open? If open I would like to work on this.

**Comment by ovflowd** [comment] 2023-10-04 08:57
The issue is ready now, as the dependent "Select" got merged.

**Comment by ovflowd** [comment] 2023-10-04 08:59
@bmuenzenmeyer I believe the issue description might need a little update based on the codebase of the Component

**Comment by HeetVekariya** [comment] 2023-10-04 09:02
I would like to work on this issue

**Closed as completed** 2023-10-06 00:01 UTC
Labels: help wanted, good first issue, website redesign, hacktoberfest
