### ISSUE TITLE
Getting 500 for https://nodejs.org/dist/v12.7.0/

### ISSUE THREAD

**Issue by mogindi** [nodejs/nodejs.org#3077] opened 2020-04-06 10:42 UTC
Saw other bug reports mentioning 500s but thought the more info the better :)

**Comment by BoazWarshawsky** [comment] 2020-04-06 10:49
I am getting 500 for that URL: https://nodejs.org/dist/v12.16.1/node-v12.16.1-darwin-x64.tar.gz

**Comment by XhmikosR** [comment] 2020-04-06 11:25
Duplicate of #3075, please look for existing issues before creating a new one.

**Closed as completed by XhmikosR** 2020-04-06 11:25 UTC
