### ISSUE TITLE
No installation doc

### ISSUE THREAD

**Issue by Chris-AGR** [nodejs/nodejs.org#1491] opened 2017-11-29 20:12 UTC
* **nodejs.org**:
* **All browsers**:
* **windows**:

There is no installation guide/doc for windows using node.exe file.  Due to administrative and firewall so folks are unable to download the msi installer.

**Comment by fhemberger** [comment] 2017-12-19 08:59
What would you expect from an installation guide in this case?

**Comment by Chris-AGR** [comment] 2017-12-19 14:33
Self extracting and installing downloads are great, I prefer the ease due to the work load we enjoy. Unfortunately, because of heightened security rules on the network, those types of files (zip, msi, etc.) are not allowed to be downloaded. Oddly enough, executables are able to be properly scanned and so are allowed. Without the availability of the self installers it makes demoing a system like nodejs more time consuming and difficult to achieve.

A short guide on how to install nodejs using the executable would be a great addition to the nodejs website. A short and simple step by step approach would work. Although it seems elementary, and is, at least two people I know have been deterred from trying out nodejs.  My guess is there are many more.

thanks.

**Comment by gibfahn** [comment] 2017-12-28 13:15
>A short guide on how to install nodejs using the executable would be a great addition to the nodejs website. A short and simple step by step approach would work.

Don't you just download and double-click on the executable (or run `.\node` on the command line)? Is it adding node to the path that you would like to be documented?

cc/ @nodejs/platform-windows

**Comment by seishun** [comment] 2017-12-28 13:22
Yes, it's just an executable file that you either double-click or run from the command line, exactly like you would if you had installed it with the installer. Where you place this executable is completely up to you, so there is nothing to document.

I suggest closing this as an answered question.

**Comment by gibfahn** [comment] 2017-12-28 14:15
I'll close for now, but we can reopen if @Chris-AGR still feels there is information that needs documenting.

**Closed as completed by gibfahn** 2017-12-28 14:15 UTC
Labels: content

**Comment by Chris-AGR** [comment] 2017-12-29 21:45
@gibfahn 

I'm really trying to demo react-native.  If I just download and double-click on the nodejs executable and try this command:

`npm install -g create-react-native-app`

I get the message "npm should be run outside of the node repl, in your normal shell."

If I run command in the normal shell I get the message:

"'npm' is not recognized as an internal or external command, operable program or batch file."

So, some small installation guide would be helpful for folks like me trying to install with only the executable.
thanks.

**Comment by daxlab** [comment] 2017-12-30 03:03
@Chris-AGR I think npm is not in your path.

**Comment by gibfahn** [comment] 2017-12-30 19:50
@Chris-AGR the problem is that npm is a load of javascript files, not part of the node executable. In fact the `node.exe` is not particularly useful for most people as it's missing npm, so you can't install any modules with it.

If you download and extract the zip files (on a computer that's not behind the firewall) you'll see that it contains the `node.exe` binary, and also lots of npm files (and the `.msi` is basically the zip + a built-in installation script). You need all of those things to actually use node.

Also, if you're not allowed to download `.zip` files, then you probably won't be able to use `npm`, as `npm install` downloads the modules as tarballs, and if `.zip` is blocked, `.tar.gz` probably will be too.
