### ISSUE TITLE
500 Internal Server Error on Debugging - Getting Started guide

### ISSUE THREAD

**Issue by deisner** [nodejs/nodejs.org#4549] opened 2022-04-18 20:36 UTC
- **URL**: https://nodejs.org/en/docs/guides/debugging-getting-started/
- **Browser version**: Firefox 99.0.1, Chrome 100.0.4896.127
- **Operating system**: macOS 12.3.1

Not much more to add -- I get a 500 upon visiting the getting started guide for debugging.

**Comment by carter-thaxton** [comment] 2022-04-18 20:40
Worse, visiting anything in the downloads area also fails, which is used by automated scripts, CI, etc.

https://nodejs.org/download/release/latest-gallium/
https://nodejs.org/download/release/v16.10.0/

**Comment by Trott** [comment] 2022-04-18 20:49
> Worse, visiting anything in the downloads area also fails, which is used by automated scripts, CI, etc.
> 
> https://nodejs.org/download/release/latest-gallium/ https://nodejs.org/download/release/v16.10.0/

Known intermittent issue. Duplicate of https://github.com/nodejs/nodejs.org/issues/4495.

**Closed as completed by Trott** 2022-04-18 20:49 UTC
