### ISSUE TITLE
Cannot download Windows binaries

### ISSUE THREAD

**Issue by kayb-proxora** [nodejs/nodejs.org#5471] opened 2023-07-04 08:25 UTC
### URL:

https://nodejs.org/dist/v18.16.1/node-v18.16.1-win-x64.zip

### Browser Name:

Chrome

### Browser Version:

Current

### Operating System:

Windows 11

### How to reproduce the issue:

If I try to download any Windows binary it's running in a timeout.

Downloads of Linux binaries, etc. are working fine, only Windows binaries are running into a timeout.

**Comment by ovflowd** [comment] 2023-07-04 08:44
Closing as duplicate of https://github.com/nodejs/nodejs.org/issues/4495

We're having some unusually high-loads this morning.

**Closed as not planned by ovflowd** 2023-07-04 08:44 UTC
