### ISSUE TITLE
Make Download buttons show packages for major Linux distros

### ISSUE THREAD

**Issue by mikemaccana** [nodejs/nodejs.org#1297] opened 2017-07-13 10:00 UTC
Related to #1233 

Currently the download buttons show

 - Windows installer/packages
 - Mac installer
 - Source code

Most Linux users don't want to compile their own node. This makes security updates harder - yum/apt auto updating would easily get 8.1.4 today, but compiled users would have to know their node is out of date then download and build node again. 

There are excellent, well maintained packages for Ubuntu/Debian and RHEL/Fedora/CentOS but they're **really** hard to find 

<img width="1253" alt="screenshot_7" src="https://user-images.githubusercontent.com/172594/28161097-20806274-67ba-11e7-8b42-db28884bfc56.png">

Suggestion:

 - Linux packages should be given more prominence than source code 
 - Debian/Ubuntu and RHEL/Fedora/CentOS instructions should be shown at the same level as Windows and Mac packages

Less popular distros (Arch etc) should still be linked as usual.

See the excellent RethinkDB download page:

<img width="835" alt="screenshot_6" src="https://user-images.githubusercontent.com/172594/28161198-7df9d1b0-67ba-11e7-89a5-54cde131d333.png">

Happy to work on this, but would like to solicit feedback first.

**Comment by mhdawson** [comment] 2017-07-13 13:16
There are already tar.xz files with a pre-built distro  for linux so linux users don't have to compile their own. 

The other data point is if you go to the main page for nodejs.org, it already figures out you are on linux and provides a link to those downloads.

**Comment by mikemaccana** [comment] 2017-07-13 16:13
- .tar.xz's have a similar issue: they won't get security updates along with the rest of the OS. 
 - Yep, front page should go straight to Linux package instructions (rather than the `.xz`)

**Comment by fhemberger** [comment] 2017-07-14 03:54
Duplicate of #676.

**Comment by fhemberger** [comment] 2017-07-16 04:06
I really like the design of the RethinkDB download page. Would be interesting to see if we can come up with something similar matching our needs.

There was always talk about a redesign of the entire site, so larger content restructuring tasks have been avoided, but with @mikeal no longer in the driver seat, I don't know if somebody still has plans for that.

**Comment by mikemaccana** [comment] 2017-07-17 11:52
Hah @fhemberger I didn't realise I'd already raised this. Sorry about the dupe!

**Comment by bnb** [comment] 2017-07-17 16:21
@fhemberger We also talked about the redesign in the last Community Committee meeting. This is definitely a consideration for @leo, as he just shared that he'd be able to start working on this now (ref: https://github.com/nodejs/nodejs.org-new/issues/4#issuecomment-313538006) 💥

**Comment by fhemberger** [comment] 2017-07-17 18:35
@bnb Thanks! Is there a way for interested @nodejs/website folks to hop on the next call or something? With @mikeal gone I feel a bit out of the loop, to be honest.

**Comment by bnb** [comment] 2017-07-24 15:53
@fhemberger Absolutely. Created an issue in the CommComm repo: https://github.com/nodejs/community-committee/issues/95

**Comment by fhemberger** [comment] 2017-12-21 15:30
Closing this as duplicate, see #676.

**Closed as completed by fhemberger** 2017-12-21 15:30 UTC
Labels: design
