### ISSUE TITLE
Markdown not rendering correctly

### ISSUE THREAD

**Issue by a0viedo** [nodejs/nodejs.org#2104] opened 2019-02-21 12:31 UTC
* **URL**: https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/
* **Browser version**: Version 72.0.3626.109 (Official Build) (64-bit)
* **Operating system**: Windows

I'm not sure why, but at one portion of the guide content with italic is not being rendering correctly. I checked to grab and paste the entire markdown in `marked`'s demo website and it renders properly.
![image](https://user-images.githubusercontent.com/2440935/53169093-12ad1400-35bb-11e9-9780-dd950d6ddecb.png)

**Comment by ronperris** [comment] 2019-02-21 22:10
@a0viedo I reproduced the issue [here](https://marked.js.org/demo/?text=_and%20there%20are%20no%20timers%20scheduled_%2C&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.5.2). Looks like a bug in marked@0.5.2 which is used by metalsmith-markdown.

**Comment by fhemberger** [comment] 2019-02-22 05:35
Fixed by #2108.

**Closed as completed by fhemberger** 2019-02-22 05:35 UTC
