### ISSUE TITLE
404 error at https://nodejs.org/dist/latest-v6.x/docs/api

### ISSUE THREAD

**Issue by mrspaghetti** [nodejs/nodejs.org#1391] opened 2017-10-06 16:37 UTC
* **URL**:
* **Browser version**:
* **Operating system**:

**Comment by knksmith57** [comment] 2017-10-06 17:29
looks like this isn't isolated to LTS docs, but _all_ linked API doc revisions:
```
❯ curl -iI https://nodejs.org/docs/latest-v4.x/api/
HTTP/1.1 404 Not Found
Date: Fri, 06 Oct 2017 17:26:55 GMT
Content-Type: text/html
Connection: keep-alive
Set-Cookie: __cfduid=d2d6164c76c80f031477a5d16976158131507310815; expires=Sat, 06-Oct-18 17:26:55 GMT; path=/; domain=.nodejs.org; HttpOnly
CF-Cache-Status: HIT
Server: cloudflare-nginx
CF-RAY: 3a9a5416d9df58f1-DFW
```

affecting:
* https://nodejs.org/docs/
* https://nodejs.org/docs/latest-v0.10.x/api/
* https://nodejs.org/docs/latest-v0.12.x/api/
* https://nodejs.org/docs/latest-v4.x/api/
* https://nodejs.org/docs/latest-v5.x/api/
* https://nodejs.org/dist/latest-v6.x/docs/api/
* https://nodejs.org/dist/latest-v8.x/docs/api

can we get someone from core to look at this pretty please?

@jasnell or @mikeal maybe?

**Comment by knksmith57** [comment] 2017-10-06 17:32
money says this is related to #1387.

@fhemberger is it possible this is simply a caching issue w/ cloudflare?

**Comment by fhemberger** [comment] 2017-10-06 17:57
Seems to be a Cloudflare issue. Works fine for me (tested from Germany and via VPN from the US).

**Comment by knksmith57** [comment] 2017-10-06 18:38
Links are still busted for me.

For the rest of the world, static mirrors:
* http://nodejs-api-docs.s3-website-us-west-2.amazonaws.com/6.11.5/
* http://nodejs-api-docs.s3-website-us-west-2.amazonaws.com/8.6.1/

happy to add more versions at request if the issue persists.

**Comment by fhemberger** [comment] 2017-10-06 18:52
Hello @nodejs/build, can you please look into this?

**Comment by joaocgreis** [comment] 2017-10-06 19:38
Links also work for me.

I've cleared the Cloudflare cache, don't know if that will help.

This is a duplicate of https://github.com/nodejs/nodejs.org/issues/1390 and https://github.com/nodejs/build/issues/905 .

**Comment by fhemberger** [comment] 2017-10-06 19:50
Closing this one in favor of nodejs/build#905. Please comment there If the issue still persists on your side.

**Closed as completed by fhemberger** 2017-10-06 19:50 UTC
Labels: external/build

**Comment by refack** [comment] 2017-10-07 22:29
@fhemberger trying to figure out what CF is caching... Was there a time window where the `/docs/*` paths didn't work?

**Comment by gibfahn** [comment] 2017-10-07 22:39
Can we comment on https://github.com/nodejs/build/issues/905 instead? Otherwise we just get duplicates.
