### ISSUE TITLE
The event loop ascii art is broken

### ISSUE THREAD

**Issue by juanarbol** [nodejs/nodejs.org#6337] opened 2024-02-12 02:05 UTC
### URL:

https://nodejs.org/en/guides/event-loop-timers-and-nexttick/

### Browser Name:

Chrome

### Browser Version:

121.0.6167.160 (Official Build) (arm64)

### Operating System:

macOS

### How to reproduce the issue:

1. Visit https://nodejs.org/en/guides/event-loop-timers-and-nexttick/
2. Have the ascii art correctly as it used to be https://web.archive.org/web/20231226234524/https://nodejs.org/en/guides/event-loop-timers-and-nexttick/
3. ascii art is broken

The code is ok, but I think `shikiji` is trimming empty spaces

![Screenshot 2024-02-11 at 9 03 49 PM](https://github.com/nodejs/nodejs.org/assets/17013303/cf18fa53-29d1-4291-847b-595a77dbe074)

**Comment by ovflowd** [comment] 2024-02-12 10:42
Interesting. We can check if Shikiji has an option to not trim empty spaces.

**Comment by juanarbol** [comment] 2024-02-12 19:17
I tried to make a quick fix w/ no success, maybe someone here can fix that faster than me

**Comment by ovflowd** [comment] 2024-02-13 18:52
I'm making a PR to address this.

**Comment by ovflowd** [comment] 2024-02-13 19:11
Hmm, I'm actually unable to find a fix for this. It is a combination of our word wrapping for code + other CSS shenanigans.

**Comment by ovflowd** [comment] 2024-02-13 20:14
Found a solution for it. The issue is the font-family, pretty much.

**Closed as completed** 2024-02-14 09:08 UTC

**Comment by juanarbol** [comment] 2024-02-14 19:36
It was not that trivial. Thanks!
