### ISSUE TITLE
Node js website showing client exception

### ISSUE THREAD

**Issue by PrasathHari** [nodejs/nodejs.org#5567] opened 2023-07-30 15:30 UTC
### URL:

https://nodejs.org/en

### Browser Name:

Edge

### Browser Version:

115.0.1901.188 (Official build) (64-bit)

### Operating System:

Windows 11

### How to reproduce the issue:

1. Search for node js in the Google/bing search
2. Open the nodejs.org link
3. The below error is shown when I visit any of the page in nodejs.org website
![image](https://github.com/nodejs/nodejs.org/assets/33195878/faa7e697-4ba7-4ca0-b2e0-3c14ba4ce45a)

**Comment by bmuenzenmeyer** [comment] 2023-07-30 15:39
![image](https://github.com/nodejs/nodejs.org/assets/298435/a755c6cb-42d7-4774-8b91-1fdf361f20e5)

**Comment by ovflowd** [comment] 2023-07-30 15:42
Closing as duplicate of https://github.com/nodejs/nodejs.org/issues/5568

**Closed as not planned by ovflowd** 2023-07-30 15:42 UTC
