### ISSUE TITLE
Downloads page error 500 Internal Server Error

### ISSUE THREAD

**Issue by volumio** [nodejs/nodejs.org#5591] opened 2023-07-31 22:19 UTC
### URL:

https://nodejs.org/dist/v18.17.0/

### Browser Name:

Chrome

### Browser Version:

N\A

### Operating System:

Windows 11

### How to reproduce the issue:

1. From nodejs download page: https://nodejs.org/it/download
2. Click on "All Downloads"
3. Nginx reports 500 error

Seems that all downloads except latest are affected. Probably an NGINX misconf that went live? 

NOTE: I discovered this since our CI fails our builds since it downloads a specific version of Node headers and their checksum (namely: https://nodejs.org/download/release/v14.15.4/node-v14.15.4-headers.tar.gz and https://nodejs.org/download/release/v14.15.4/SHASUMS256.txt)

As a further precaution, I would recommend updating the status page check to also verify older downloads (as the status page reports all system are operating normally)

Thanks for taking care of it

**Comment by scotthogan** [comment] 2023-07-31 22:26
I just came across this as well, https://nodejs.org/download/release/ returning an nginx 500 page. In our case, some tooling is using [@pnpm/node.fetcher](https://www.npmjs.com/package/@pnpm/node.fetcher) for installing node versions, which downloads from nodejs.org under the hood. We started seeing failures from this starting around 9 hours ago.

**Comment by Coldarn** [comment] 2023-07-31 22:27
This is breaking my CI as well, intermittent failures to download: https://nodejs.org/download/release/v16.19.1/node-v16.19.1-linux-x64.tar.gz

**Comment by volumio** [comment] 2023-07-31 22:30
Seems to be back to normal now, if that was a reaction, kudos that was quick. Thanks!

**Comment by Coldarn** [comment] 2023-07-31 23:15
My builds are passing again, seems resolved?

**Comment by ovflowd** [comment] 2023-08-01 07:13
Duplicate of https://github.com/nodejs/nodejs.org/issues/4495

**Closed as not planned by ovflowd** 2023-08-01 07:13 UTC

**Comment by ovflowd** [comment] 2023-08-01 07:15
> My builds are passing again, seems resolved?

No, it was not resolved 8 hours ago. This issue is sorta intermittent, based on how much traffic was coming to the server.

**Comment by volumio** [comment] 2023-08-01 07:27
Confirm it's resolved on my end. Thanks for the action and explanation on the other issue
