### ISSUE TITLE
500 Internal Server Error When Downloading NodeJS v20.5.0

### ISSUE THREAD

**Issue by cerebralmind** [nodejs/nodejs.org#5667] opened 2023-08-24 17:59 UTC
### URL:

https://nodejs.org/dist/v20.5.0/node-v20.5.0-linux-x64.tar.xz

### Browser Name:

curl, wget, chrome, firefox, etc

### Browser Version:

N/A

### Operating System:

Linux, OSX (N/A since this is an internal server error)

### How to reproduce the issue:

Open the following link https://nodejs.org/dist/v20.5.0/node-v20.5.0-linux-x64.tar.xz

**Comment by ovflowd** [comment] 2023-08-24 19:05
Duplicate of https://github.com/nodejs/nodejs.org/issues/4495

**Closed as not planned by ovflowd** 2023-08-24 19:05 UTC
