### ISSUE TITLE
Distribution download links not working

### ISSUE THREAD

**Issue by tomgreco** [nodejs/nodejs.org#5976] opened 2023-10-10 17:23 UTC
### URL:

Downloading https://nodejs.org/dist/v16.15.1/node-v16.15.1-darwin-x64.tar.xz

### Browser Name:

CI and Chrome and terminal

### Browser Version:

?

### Operating System:

All

### How to reproduce the issue:

Downloading https://nodejs.org/dist/v18.9.1/node-v18.9.1-darwin-arm64.tar.xz...

Timesout

Downloading https://nodejs.org/dist/v16.15.1/node-v16.15.1-darwin-x64.tar.xz...

Times out

**Comment by ovflowd** [comment] 2023-10-10 17:45
Duplicate of #4495

**Closed as not planned by ovflowd** 2023-10-10 17:45 UTC
