### ISSUE TITLE
Getting 500 for https://nodejs.org/dist/v10.15.0/

### ISSUE THREAD

**Issue by afractal** [nodejs/nodejs.org#3079] opened 2020-04-06 10:59 UTC
This happens for other versions as well.
![image](https://user-images.githubusercontent.com/8417583/78551678-5c2fe100-7806-11ea-97c9-4ff0bde849a9.png)

**Comment by XhmikosR** [comment] 2020-04-06 11:25
Duplicate of #3075, please look for existing issues before creating a new one.

**Closed as completed by XhmikosR** 2020-04-06 11:25 UTC
