### ISSUE TITLE
Improve doc readability

### ISSUE THREAD

**Issue by octref** [nodejs/nodejs.org#919] opened 2016-09-25 21:11 UTC
- **URL**: https://nodejs.org/api/fs.html

This is how the doc looks on my 15 inch RMBP using half screen. Can't even show a full function definition.

Please improve your media queries or font-size. I'm not a mobile user.

![image](https://cloud.githubusercontent.com/assets/4033249/18818254/b74f4d9e-8329-11e6-83cd-762de6e1ff6d.png)

**Comment by phillipj** [comment] 2016-09-26 18:57
I can confirm this doesn't look optimal on a retina macbook atm. This is the caused by a media query I assume is supposed to be targeting iPad-ish devices.

``` css
@media only screen and (max-width: 1024px) {
  #content {
    font-size: 2.5em;
    overflow: visible;
  }
  ..
}
```

https://github.com/nodejs/node/blob/master/doc/api_assets/style.css#L463

I don't have a iPad (retina or not) at hand, so I haven't been able to test if the big font size is neccessary on those devices.. It maybe time to re-visit some of these media queries.

/cc @nodejs/documentation

**Comment by Fishrock123** [comment] 2016-09-27 16:51
Looping myself in, I had a go at working on some if the CSS the other week, but didn't finish it yet.

**Comment by phillipj** [comment] 2016-10-18 18:51
@Fishrock123 guessing that work ended up in https://github.com/nodejs/node/pull/8811?

**Comment by Fishrock123** [comment] 2016-11-08 18:23
No sorry, that was for something else. This persists I'm pretty sure.

**Comment by diagramatics** [comment] 2017-01-02 05:21
Considering that the `font-size` could go from 25px to as high as 35px on a portrait oriented iPad, I agree this could be overkill. I'm pretty sure the default size of 18px would already suffice on an iPad, if not, probably just a small bump to 21px.

We could just remove the media queries completely. If that's the verdict I can go and change it.

**Comment by octref** [comment] 2017-03-05 16:06
I'm glad to find out changing a few css lines would take more than half a year.

Seriously. Just changing the font-size to 1.6em and it'll look much better.

![image](https://cloud.githubusercontent.com/assets/4033249/23588976/6d5986d0-0193-11e7-99a4-af64460a3a8c.png)

**Comment by gibfahn** [comment] 2017-03-05 16:16
@octref care to submit a PR?

**Comment by octref** [comment] 2017-03-05 16:21
Not really, and I don't have an iPad to test if the website would look good on iPad (seems the original intent for this media query is to do so).

But it's really just change the value here https://github.com/nodejs/node/blob/master/doc/api_assets/style.css#L490 and make sure it's good on iPad.

**Comment by gibfahn** [comment] 2017-03-05 16:28
PR raised: https://github.com/nodejs/node/pull/11695

**Comment by bnoordhuis** [comment] 2017-03-05 17:05
> I'm glad to find out changing a few css lines would take more than half a year.

You don't get to use that tone.  Most people here are volunteers so pipe down.

**Comment by octref** [comment] 2017-03-05 17:58
I apologize. I wish the usability of the doc website can be given more attention and improved, but I could have said that in a less entitled way.

**Comment by bnoordhuis** [comment] 2017-03-05 19:05
No worries.  Reading back what I wrote, I could have voiced it in a friendlier way too.

**Comment by fhinkel** [comment] 2017-03-09 10:01
Fixed in https://github.com/nodejs/node/commit/7c8bbe37b7a0e07a5754bc21cb00166240953f49. Looks like I don't have permission to close issues in this repo :thinking:

**Closed as completed** 2017-03-09 10:12 UTC

**Comment by octref** [comment] 2017-09-15 16:53
Just pinging people in this thread, this issue hasn't been resolved for a whole year.

How it looks on half of my 15 inch macbook screen today: 
![image](https://user-images.githubusercontent.com/4033249/30494011-5239e29a-99fb-11e7-8ad4-edeec23ac288.png)

Relevant CSS:
![image](https://user-images.githubusercontent.com/4033249/30494118-b51e626e-99fb-11e7-8018-9e7e2fba7c56.png)

**Comment by thefourtheye** [comment] 2017-09-15 17:51
I think https://github.com/nodejs/node/pull/15430 is related.

**Comment by octref** [comment] 2017-10-03 18:50
@bnoordhuis This bug just passed its one year birthday. I don't know what tone should I use to express my frustration. I use this layout everyday and `nodejs.org/api` has been unusable for me for a whole year.

![image](https://user-images.githubusercontent.com/4033249/31143063-f1a424c4-a830-11e7-9aaa-39175beb0496.png)

**Comment by lpinca** [comment] 2017-10-03 19:02
@octref see https://github.com/nodejs/node/pull/15660.
All I can suggest is to get you hands dirty if you want to improve things.

**Comment by octref** [comment] 2017-10-03 19:09
@lpinca OK I’m glad there is ongoing effort in fixing this. Thanks for linking the issue.
