### ISSUE TITLE
Redirect issue: Older api documentation and versions redirecting to blog

### ISSUE THREAD

**Issue by dimd13** [nodejs/nodejs.org#125] opened 2015-09-10 08:22 UTC
On new site i found this link http://nodejs.org/docs/v0.12.7/api/ at news about this release https://nodejs.org/en/blog/release/v0.12.7/, but it redirect to blog main page. 
Download links takes the same,  redirect to blog main page.

I.. no no...We need older versions of node and older versions api documentation too!

**Comment by fhemberger** [comment] 2015-09-10 08:26
Duplicate of #124, use https://nodejs.org/docs/ instead.

**Comment by ellenaua** [comment] 2015-09-10 09:16
+1 and this is urgent, we have failing builds because http://nodejs.org/dist/v0.10.21/node-v0.10.21.tar.gz cannot be downloaded

**Comment by drobiazko** [comment] 2015-09-10 09:18
node-gyp is downloading node.js during the build. Using https://nodejs.org/docs/  does not really help us. The node.js folks should maintain backward-compatibility when building the new website.

**Comment by fhemberger** [comment] 2015-09-10 09:20
@ellenaua @drobiazko Wrong issue: #124

**Comment by rvagg** [comment] 2015-09-10 09:46
my fault
should be fixed now, your browser may be caching the bad redirect though

**Closed as completed by rvagg** 2015-09-10 09:46 UTC
Labels: external/build
