### ISSUE TITLE
Can't download Latest Version of Node.js from Nodejs.org

### ISSUE THREAD

**Issue by interglobalmedia** [nodejs/nodejs.org#1193] opened 2017-04-04 23:15 UTC
* **URL**: https://nodejs.org/en/
* **Browser version**: Version 57.0.2987.133 (64-bit)
* **Operating system**: 10.12 Mac OS Sierra

Can't download the latest version of Node (7.8.0) from Nodejs.org
Getting Error 522 
nodejs.org
Host
Error

**Comment by levlaz** [comment] 2017-04-04 23:24
This is a duplicate of https://github.com/nodejs/nodejs.org/issues/1191

**Comment by vsemozhetbyt** [comment] 2017-04-04 23:37
Thank you for the report. I will go ahead and close it as a duplicate. Please, track the https://github.com/nodejs/nodejs.org/issues/1191.

**Closed as completed by vsemozhetbyt** 2017-04-04 23:37 UTC

**Comment by interglobalmedia** [comment] 2017-04-04 23:40
Thanks! Already following the issue there.
