### ISSUE TITLE
Cannot download distribution (error 500)

### ISSUE THREAD

**Issue by basz** [nodejs/nodejs.org#5718] opened 2023-08-30 14:44 UTC
### URL:

https://nodejs.org/dist/v18.17.1/node-v18.17.1-linux-arm64.tar.gz

### Browser Name:

any

### Browser Version:

any

### Operating System:

any

### How to reproduce the issue:

My github actions download https://nodejs.org/dist/v18.17.1/node-v18.17.1-linux-arm64.tar.gz which suddenly started getting internal server error.

Tried in locally in chrome. same.

I can download any file inside this directory https://nodejs.org/dist/v18.17.1/ except node-v18.17.1-linux-arm64.tar.gz

My phone (connecting over 4G) also

**Comment by ovflowd** [comment] 2023-08-30 14:52
Duplicate of https://github.com/nodejs/nodejs.org/issues/4495

**Closed as not planned by ovflowd** 2023-08-30 14:52 UTC
