### ISSUE TITLE
Open Directory

### ISSUE THREAD

**Issue by real-zit** [nodejs/nodejs.org#4067] opened 2021-08-24 07:11 UTC
When we enter "nodejs.org/download" we go  to the open directory
* **www.nodejs.org/download**:

**Comment by Trott** [comment] 2021-08-25 04:41
Yes. That is an intentional feature, not a bug. A directory listing is quite useful for that particular directory and its subdirectories. Same for `dist`.  I'm going to optimistically close this, but if you happen to find an issue (for example, the ability to navigate to directories above or otherwise outside the webroot, or the disclosure of information unintended to be disclosed by the directory listing), please by all means comment.

**Closed as completed by Trott** 2021-08-25 04:41 UTC
