### ISSUE TITLE
/en/docs and /en/about raises a 500: Internal Server Error

### ISSUE THREAD

**Issue by LavransBjerkestrand** [nodejs/nodejs.org#5805] opened 2023-09-19 13:33 UTC
### URL:

https://nodejs.org/en/docs

### Browser Name:

Safari

### Browser Version:

18615.3.12.11.2

### Operating System:

macOS Ventura, 13.5.2 (22G91)

### How to reproduce the issue:

[https://nodejs.org/en/docs](https://nodejs.org/en/docs) produces a NextJS 500 Internal Server Error page.

Seems to work for other languages than English.

<img width="598" alt="image" src="https://github.com/nodejs/nodejs.org/assets/11774195/0141b953-db0e-42f5-bda0-3229dc24e1d4">

**Comment by bmuenzenmeyer** [comment] 2023-09-19 13:51
duplicate of #5804 - thanks for reporting

**Closed as not planned by bmuenzenmeyer** 2023-09-19 13:51 UTC
