### ISSUE TITLE
Add page navigation buttons next and previous

### ISSUE THREAD

**Issue by princerachit** [nodejs/nodejs.org#2144] opened 2019-03-08 10:27 UTC
Current feature: The tutorials page contains a set of links to tutorials.
Issue: When I navigate to a page I don't have the option to go to next or previous page in the tutorial. Therefore, I have to go back to main page and then click on the link to next tutorial.
Solution: Add navigation buttons at the page bottom.

**Comment by fhemberger** [comment] 2019-03-08 12:26
Duplicate of https://github.com/nodejs/nodejs.org/issues/2011#issuecomment-457492623

The tutorial section will be replaced/reworked entirely on the upcoming relaunch.

**Closed as completed by fhemberger** 2019-03-08 12:26 UTC
