### ISSUE TITLE
Infrastructure providers page on website

### ISSUE THREAD

**Issue by rvagg** [nodejs/nodejs.org#1521] opened 2017-12-19 00:51 UTC
We have an action item in @nodejs/build to put something onto nodejs.org to promote our infrastructure providers but nobody seems to have time to make it happen, it'd be great if we could find a volunteer to help make this happen.

We currently keep this content in this section of our README but would like to bring it up to the top level and have it on our website: https://github.com/nodejs/build/#infrastructure-providers

All of our build, release and hosting infrastructure is donor-provided (except for the stuff the Foundation itself uses), and we'd like to express thanks to these donors and also promote how proud we are of the community of companies and individuals that have contributed and continue to contribute key resources. It also helps pull in new donors if we have a bigger portfolio of benefits for donating—having your logo on nodejs.org is a nice perk.

I was thinking that it might be easiest if we just maintain the content on our README and have the website pull out that section for the content so we don't have to maintain it in two places? Happy to hear other suggestions of course. As for placement, perhaps under About as "Infrastructure"?

**Comment by Trott** [comment] 2017-12-19 01:17
@nodejs/website

**Comment by fhemberger** [comment] 2017-12-19 08:56
Duplicate of #1257.

**Closed as completed** 2017-12-28 09:03 UTC
