### ISSUE TITLE
Some links returning 500 Internal Request Error

### ISSUE THREAD

**Issue by neilobremski** [nodejs/nodejs.org#4550] opened 2022-04-18 20:48 UTC
We ran into this when a Heroku deployment failed trying to get this URL:

- https://nodejs.org/download/release/v10.11.0/node-v10.11.0-headers.tar.gz

I then tried some other URLs and found the same issue:

- https://nodejs.org/en/blog/release/v16.14.1/
- https://nodejs.org/en/blog/release/v17.8.0/

This likely happens on all browsers, platforms, etc. but I specifically found it on ChromeOS and Debian 10.

**Comment by Trott** [comment] 2022-04-18 20:50
Duplicate of https://github.com/nodejs/nodejs.org/issues/4495

**Closed as completed by Trott** 2022-04-18 20:50 UTC
