### ISSUE TITLE
canonical md link for 404 page

### ISSUE THREAD

**Issue by Trott** [nodejs/nodejs.org#3430] opened 2020-10-03 14:05 UTC
Anyone know why this appears in the source when you get a 404 page on the website?

```html
<link rel="canonical" href="https://nodejs.org/en/404.md/">
```

The md file does not exist, so...broken link. Should be `https://nodejs.org/en/404.html`. I haven't spent time trying to find where this is generated, but didn't want to leave it unaddressed so...opening an issue.

**Comment by nschonni** [comment] 2020-10-03 15:46
Nothing obviously pops into my head. But here are my two hunches:
- Something baked into Metalsmith
- Something in the nginx config used to do the language detection/fallback in nodejs/build

**Comment by XhmikosR** [comment] 2021-02-14 18:32
This is definitely something in this repo. It looks that 404.md has `permalink: false` and this causes the issue. Unsure how to work around it.

**Comment by Trott** [comment] 2023-01-13 23:53
This is still an issue. I'm not sure why it was closed.

**Comment by AugustinMauroy** [comment] 2023-01-14 10:25
I was not able to reproduce the outcome on the current version. Maybe someone can enlighten me.

**Comment by nschonni** [comment] 2023-01-14 16:44
1. Open <https://nodejs.org/fr/foo>
2. `<link rel="canonical" href="https://nodejs.org/fr/404.md/">` is in the head, as the issue describes. An MD file that doesn't exist in the repo

**Comment by AugustinMauroy** [comment] 2023-01-17 08:28
AH! When I did `cmd+f '404.md'` it told me that there was nothing...

**Comment by ovflowd** [comment] 2023-01-18 16:51
> I was not able to reproduce the outcome on the current version. Maybe someone can enlighten me.

That's no reason to close the issue without writing any message.

**Comment by ovflowd** [comment] 2023-03-12 14:02
Canonical links got removed from 404.

**Closed as completed by ovflowd** 2023-03-12 14:02 UTC
