### ISSUE TITLE
Download link on Home page is not working

### ISSUE THREAD

**Issue by thenishchalraj** [nodejs/nodejs.org#1601] opened 2018-03-25 11:10 UTC
![screenshot from 2018-03-25 10-12-10](https://user-images.githubusercontent.com/15857220/37874269-9c7260aa-3049-11e8-8db1-486061b771eb.png)
![screenshot from 2018-03-25 10-12-35](https://user-images.githubusercontent.com/15857220/37874271-9caf6388-3049-11e8-85d5-6a4646df7f5f.png)
![screenshot from 2018-03-25 10-13-23](https://user-images.githubusercontent.com/15857220/37874272-9ce3a382-3049-11e8-8202-8304907fb75d.png)

* **URL**: https://nodejs.org/en/ and https://nodejs.org/en/download/
* **Browser version**: Firefox quantum 58.0.1
* **Operating system**: Kali Linux 

**Description:**
   The download link for the "recommended version" of nodejs (i.e. shown on the website , in my case it is _Linux x64_) does not really links to the downloadable file _8.10.0. LTS_, rather it opens the file (*node-v8.10.0-linux-x64.tar.xz*) in the browser (which is of course non readable).
Changing the URL from "_**https://nodejs.org/dist/v8.10.0/node-v8.10.0-linux-x64.tar.xz**_" to "https://nodejs.org/dist/v8.10.0/" lands on an Index page with all the links to the files for different distro and can't be downloaded as each of them has the same issue.
Also, I want to add that, links on "_**https://nodejs.org/en/download/**_" aren't working too except for _Windows Installer, Windows Binary_ and _Docker Image_.

**Mitigation:**
  Please provide a downloadable link behind the click for the version and distribution you are showing it. Other than having a tour on the site for the same, it will be good if users can download from the home page only.

**Comment by tniessen** [comment] 2018-03-25 11:24
Seems to be related to https://github.com/nodejs/nodejs.org/issues/1600. In the meantime, you should be able to download releases by right-clicking the link and selecting "Save target as...".

**Comment by fhemberger** [comment] 2018-03-26 09:44
Closing as duplicate of #1600.

**Closed as completed by fhemberger** 2018-03-26 09:44 UTC
