### ISSUE TITLE
Links to changelogs are broken

### ISSUE THREAD

**Issue by mhdawson** [nodejs/nodejs.org#5664] opened 2023-08-22 19:01 UTC
### URL:

https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.8.0

### Browser Name:

Chrome

### Browser Version:

Any

### Operating System:

Windows

### How to reproduce the issue:

Go to page that shows changelog (https://github.com/nodejs/node/blob/main/CHANGELOG.md). Select one of the links, for example:

https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.8.0

I just see a "Error loading page"

**Comment by ovflowd** [comment] 2023-08-23 08:48
There's already an issue on `nodejs/node` for this one, @mhdawson, and this is a GitHub bug 👀

**Comment by ovflowd** [comment] 2023-08-23 08:48
Duplicate of https://github.com/nodejs/node/issues/48833

**Closed as not planned by ovflowd** 2023-08-23 08:48 UTC
