### ISSUE TITLE
500 http code for taking node-v9.5.0-linux-x64.tar.gz distributive

### ISSUE THREAD

**Issue by ddorkin** [nodejs/nodejs.org#3076] opened 2020-04-06 08:23 UTC
Can not download 
https://nodejs.org/dist/v9.5.0/node-v9.5.0-linux-x64.tar.gz
receive 500 error code

**Browser version:** 
Google Chrome | 80.0.3987.149 (Official Build) (64-bit) (cohort: Stable)
**Operating system:**
Windows 10 Enterprise

Here is snapshot:
![image](https://user-images.githubusercontent.com/2884430/78537960-f25d0a80-77f8-11ea-9eed-b8187aa8cc06.png)

-- | --

**Comment by ddorkin** [comment] 2020-04-06 08:28
seems like it works again. Close the issue.

**Comment by ddorkin** [comment] 2020-04-06 08:30
UPD: it failed again ...

**Comment by Tejendi** [comment] 2020-04-06 08:45
I'm experincing the same error, when trying to get the following:
https://nodejs.org/dist/v12.5.0/node-v12.5.0-win-x64.7z

This issue is likely a duplicate of: #3075

**Comment by Skgtouch** [comment] 2020-04-06 08:47
Facing same issue.
Not able download tar.gz for any version.
Getting 500

**Comment by adjerbetian** [comment] 2020-04-06 08:49
Same with https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.gz, very slow and sometimes times out.

**Comment by loukianov** [comment] 2020-04-06 09:25
Same with all of https://nodejs.org/dist/v10.15.x/ - 500

**Comment by XhmikosR** [comment] 2020-04-06 11:25
Duplicate of #3075, please look for existing issues before creating a new one.

**Closed as completed by XhmikosR** 2020-04-06 11:25 UTC
