### ISSUE TITLE
Trademark Policy footer link goes to 404 page

### ISSUE THREAD

**Issue by jenewland1999** [nodejs/nodejs.org#6402] opened 2024-03-02 19:20 UTC
### URL:

https://beta-node-js-org.vercel.app/en

### Browser Name:

Chrome

### Browser Version:

122.0.6261.94

### Operating System:

macOS 14.3.1

### How to reproduce the issue:

1. Went to the new beta Node.js website https://beta-node-js-org.vercel.app/en
2. Clicked the "Trademark Policy" link in the footer
3. Expected it to take me to https://images.prismic.io/openjsf/69641abf-ac84-44a2-b719-ee4498d07b06_OpenJS-Foundation-Trademark-Policy-2021-01-12.docx.pdf
4. Instead it takes me to https://openjsf.org/wp-content/uploads/sites/84/2021/01/OpenJS-Foundation-Trademark-Policy-2021-01-12.docx.pdf

**Comment by AugustinMauroy** [comment] 2024-03-02 19:35
duplicate of #6401

**Comment by jenewland1999** [comment] 2024-03-02 19:40
> duplicate of #6401

@AugustinMauroy How is this a duplicate of #6401? One refers to the Trademark Policy and the other the Privacy Policy. Unless I'm missing something 😅

**Comment by AugustinMauroy** [comment] 2024-03-02 19:54
Oh wow gatcha. Sorry 
SO link for this is https://trademark-policy.openjsf.org/

**Comment by ovflowd** [comment] 2024-03-02 19:58
> Oh wow gatcha. Sorry SO link for this is [trademark-policy.openjsf.org](https://trademark-policy.openjsf.org/)

Stating the link doesn't help to fix the issue ;)

**Comment by Nyx1on** [comment] 2024-03-02 20:06
Heyy @jenewland1999 could you please assign this issue to me?

**Closed as completed** 2024-03-02 21:53 UTC
Labels: help wanted, good first issue
