### ISSUE TITLE
Page content does not update when navigating from "News" to "Downloads" page 

### ISSUE THREAD

**Issue by mikeesto** [nodejs/nodejs.org#5478] opened 2023-07-07 02:34 UTC
### URL:

https://nodejs.org/en/blog

### Browser Name:

Chrome

### Browser Version:

114.0.5735.198

### Operating System:

MacOS

### How to reproduce the issue:

1. Open https://nodejs.org/en/blog
2. Click on 'Downloads' in the top nav bar
3. The URL updates but the page content does not - I would expect to see the content for Downloads

**Comment by bmuenzenmeyer** [comment] 2023-07-07 03:02
it looks like you can reproduce the behavior in the opposite direction too

**Comment by bmuenzenmeyer** [comment] 2023-07-07 03:29
> When I debug issues, I usually stream of conscious them, so this might be way off base, but I hope it jumps starts some thoughts. 

initial triage, reading up on the next console log  `A soft navigation has been detected: https://nodejs.org/en/blog` led me to https://github.com/vercel/next.js/issues/42991

Also not certain how relevant this is because we only use the app directory for feeds from what I can tell

Here's the soft-navigation docs: https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#conditions-for-soft-navigation

I wonder if it was broken prior to this hotfix yesterday https://github.com/nodejs/nodejs.org/pull/5474 introduced to alleviate pressure on the site.

**Comment by ovflowd** [comment] 2023-07-07 16:52
This seems to be a regression caused by https://github.com/nodejs/nodejs.org/pull/5464 (which was not properly tested or rather seemed working fine) and it's fixed by https://github.com/nodejs/nodejs.org/pull/5479

**Closed as completed** 2023-07-07 16:52 UTC
