### ISSUE TITLE
Downloads of node.js source by node-gyp are returning 500

### ISSUE THREAD

**Issue by craigrva** [nodejs/nodejs.org#5588] opened 2023-07-31 20:17 UTC
### URL:

https://nodejs.org/download/release/v14.16.0/

### Browser Name:

Chrome

### Browser Version:

115.0.5790.114

### Operating System:

MacOS 13.4.1

### How to reproduce the issue:

Builds of NodeJS through node-gyp are failing due to 500 errors from nodejs.org. This is happening intermittently across all of our builds, some test nodes will fail for this reason and others will pass in the same CI run. The requests are failing on both the .tar.gz download and the SHASUMS256.txt download.

Going to the folder through the browser is also intermittently failing with 500 status.

The most recent time occurrence was a build that started at ~4:05pm EDT on 7/31

```
gyp verb content checksum node-v14.16.0-headers.tar.gz 4b44b92903a61c29af20550f9d25bfc3029657df6b5f0a12072a70360f7eedee
gyp verb tarball done parsing tarball
gyp verb check download content checksum, need to download `SHASUMS256.txt`... 
gyp verb checksum url https://nodejs.org/download/release/v14.16.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v14.16.0/SHASUMS256.txt
gyp http 500 https://nodejs.org/download/release/v14.16.0/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp verb command remove [ '14.16.0' ]
gyp verb remove using node-gyp dir: /github/home/.node-gyp
gyp verb remove removing target version: 14.16.0
gyp verb remove removing development files for version: 14.16.0
gyp ERR! configure error 
gyp ERR! stack Error: 500 status code downloading checksum
gyp ERR! stack     at Request.<anonymous> (/__w/caseflow/caseflow/client/node_modules/node-gyp/lib/install.js:293:18)
gyp ERR! stack     at Request.emit (events.js:327:22)
gyp ERR! stack     at Request.onRequestResponse (/__w/caseflow/caseflow/client/node_modules/request/request.js:1059:10)
gyp ERR! stack     at ClientRequest.emit (events.js:315:20)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:509:22)
gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
gyp ERR! stack     at addChunk (internal/streams/readable.js:309:12)
gyp ERR! stack     at readableAddChunk (internal/streams/readable.js:284:9)
gyp ERR! System Linux 5.15.0-1041-azure
gyp ERR! command "/usr/local/bin/node" "/__w/caseflow/caseflow/client/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /__w/caseflow/caseflow/client/node_modules/node-sass
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
```
```
gyp http GET https://nodejs.org/download/release/v14.16.0/node-v14.16.0-headers.tar.gz
gyp http 500 https://nodejs.org/download/release/v14.16.0/node-v14.16.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp verb command remove [ '14.16.0' ]
gyp verb remove using node-gyp dir: /github/home/.node-gyp
gyp verb remove removing target version: 14.16.0
gyp verb remove removing development files for version: 14.16.0
gyp ERR! configure error 
gyp ERR! stack Error: 500 response downloading https://nodejs.org/download/release/v14.16.0/node-v14.16.0-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/__w/caseflow/caseflow/client/node_modules/node-gyp/lib/install.js:214:14)
gyp ERR! stack     at Request.emit (events.js:327:22)
gyp ERR! stack     at Request.onRequestResponse (/__w/caseflow/caseflow/client/node_modules/request/request.js:1059:10)
gyp ERR! stack     at ClientRequest.emit (events.js:315:20)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:509:22)
gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
gyp ERR! stack     at addChunk (internal/streams/readable.js:309:12)
gyp ERR! stack     at readableAddChunk (internal/streams/readable.js:284:9)
gyp ERR! System Linux 5.15.0-1041-azure
gyp ERR! command "/usr/local/bin/node" "/__w/caseflow/caseflow/client/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /__w/caseflow/caseflow/client/node_modules/node-sass
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
```

<img width="591" alt="image" src="https://github.com/nodejs/nodejs.org/assets/109101548/ad39aba0-e1ee-4f92-9d29-b2d4af97299f">

**Comment by ovflowd** [comment] 2023-07-31 20:19
Duplicate of https://github.com/nodejs/nodejs.org/issues/4495

**Closed as not planned by ovflowd** 2023-07-31 20:19 UTC
