### ISSUE TITLE
Getting 500 for https://nodejs.org/dist/v12.16.1/node-v12.16.1-darwin-x64.tar.gz

### ISSUE THREAD

**Issue by BoazWarshawsky** [nodejs/nodejs.org#3078] opened 2020-04-06 10:50 UTC
* **URL**: https://nodejs.org/dist/v12.16.1/node-v12.16.1-darwin-x64.tar.gz

* **Browser version**: trying to download the package in Azure pipeline 
* **Operating system**: Mac OS

**Comment by XhmikosR** [comment] 2020-04-06 11:25
Duplicate of #3075, please look for existing issues before creating a new one.

**Closed as completed by XhmikosR** 2020-04-06 11:25 UTC

**Comment by BoazWarshawsky** [comment] 2020-04-06 11:29
@XhmikosR can you share some web staus page to see if something is down?

**Comment by XhmikosR** [comment] 2020-04-06 11:31
I don't think there's such a page available. This kind of issues are handled by @nodejs/build IIRC, so the issue doesn't belong to this repo.
